name: JiraissueCreate workflow

on: 
  push:
  pull_request:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: JiraissueCreate
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: RMP
        issuetype: Task
        summary: |
          github action create
        description: |
          Compare branch
      
