name: JiraissueCreate workflow

on: 
  push:
  pull_request:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: JiraissueCreate
    steps:
    - name: Jira Create issue
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: RMP
        issuetype: Task
        summary: |
          github action create
      
