name: JiraissueCreate workflow

on: 
  push:
  pull_request:

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: JiraissueCreate
      uses: atlassian/gajira-create@master
      with:
        project: RMP
        issuetype: Task
        summary: |
          Build completed for ${{ github.repository }}
        description: |
          Compare branch
      
